<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Member extends \Member implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Member' . "\0" . 'id', '' . "\0" . 'Member' . "\0" . 'title', '' . "\0" . 'Member' . "\0" . 'firstname', '' . "\0" . 'Member' . "\0" . 'surname', '' . "\0" . 'Member' . "\0" . 'street', '' . "\0" . 'Member' . "\0" . 'box', '' . "\0" . 'Member' . "\0" . 'zip', '' . "\0" . 'Member' . "\0" . 'city', '' . "\0" . 'Member' . "\0" . 'country', '' . "\0" . 'Member' . "\0" . 'phone', '' . "\0" . 'Member' . "\0" . 'businessPhone', '' . "\0" . 'Member' . "\0" . 'mobile', '' . "\0" . 'Member' . "\0" . 'mail1', '' . "\0" . 'Member' . "\0" . 'mail2', '' . "\0" . 'Member' . "\0" . 'birthday', '' . "\0" . 'Member' . "\0" . 'profession', '' . "\0" . 'Member' . "\0" . 'deathDate', '' . "\0" . 'Member' . "\0" . 'remark', '' . "\0" . 'Member' . "\0" . 'account');
        }

        return array('__isInitialized__', '' . "\0" . 'Member' . "\0" . 'id', '' . "\0" . 'Member' . "\0" . 'title', '' . "\0" . 'Member' . "\0" . 'firstname', '' . "\0" . 'Member' . "\0" . 'surname', '' . "\0" . 'Member' . "\0" . 'street', '' . "\0" . 'Member' . "\0" . 'box', '' . "\0" . 'Member' . "\0" . 'zip', '' . "\0" . 'Member' . "\0" . 'city', '' . "\0" . 'Member' . "\0" . 'country', '' . "\0" . 'Member' . "\0" . 'phone', '' . "\0" . 'Member' . "\0" . 'businessPhone', '' . "\0" . 'Member' . "\0" . 'mobile', '' . "\0" . 'Member' . "\0" . 'mail1', '' . "\0" . 'Member' . "\0" . 'mail2', '' . "\0" . 'Member' . "\0" . 'birthday', '' . "\0" . 'Member' . "\0" . 'profession', '' . "\0" . 'Member' . "\0" . 'deathDate', '' . "\0" . 'Member' . "\0" . 'remark', '' . "\0" . 'Member' . "\0" . 'account');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Member $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', array());

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', array($surname));

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStreet', array());

        return parent::getStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setStreet($street)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStreet', array($street));

        return parent::setStreet($street);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', array());

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', array($zip));

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', array());

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', array($phone));

        return parent::setPhoneNumber($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessPhoneNumber', array());

        return parent::getBusinessPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinessPhoneNumber($businessPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessPhoneNumber', array($businessPhone));

        return parent::setBusinessPhoneNumber($businessPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobileNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobileNumber', array());

        return parent::getMobileNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setMobileNumber($mobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobileNumber', array($mobile));

        return parent::setMobileNumber($mobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail1', array());

        return parent::getMail1();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail1($mail1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail1', array($mail1));

        return parent::setMail1($mail1);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail2', array());

        return parent::getMail2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail2($mail2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail2', array($mail2));

        return parent::setMail2($mail2);
    }

    /**
     * {@inheritDoc}
     */
    public function getYear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYear', array());

        return parent::getYear();
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', array());

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function getProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfession', array());

        return parent::getProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfession($profession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfession', array($profession));

        return parent::setProfession($profession);
    }

    /**
     * {@inheritDoc}
     */
    public function isStudent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStudent', array());

        return parent::isStudent();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeathDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeathDate', array());

        return parent::getDeathDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeathDate(\DateTime $deathDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeathDate', array($deathDate));

        return parent::setDeathDate($deathDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemark()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemark', array());

        return parent::getRemark();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemark($remark)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemark', array($remark));

        return parent::setRemark($remark);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccount', array());

        return parent::getAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccount(\Account $account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccount', array($account));

        return parent::setAccount($account);
    }

    /**
     * {@inheritDoc}
     */
    public function getJsonData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJsonData', array());

        return parent::getJsonData();
    }

}
